### ISSUE TITLE
Proximi Site Stats Not updating

### ISSUE THREAD

**Issue by AlexMuriithi** [Legibra/proximi#1]
The client claims to have updated the Jobs but it didn't reflect on the stats.

**Comment by AlexMuriithi** [comment]
![screenshot_6](https://user-images.githubusercontent.com/4029811/34775111-0ca94b9c-f623-11e7-9be5-67700509760f.png)

**Comment by Legibra** [comment]
Fixed

**Comment by ngarawakimani** [comment]
Fixed
