### ISSUE TITLE
Proximi contact us page moving contacts from bottom to top 

### ISSUE THREAD

**Issue by AlexMuriithi** [Legibra/proximi#2]
The client is requesting if we can move the phone number on the contact us page from the bottom to the top for quick view:

From
![screenshot_8](https://user-images.githubusercontent.com/4029811/34778447-6553a886-f62e-11e7-93b5-badd80c57726.png)

To
![screenshot_9](https://user-images.githubusercontent.com/4029811/34778448-65b0bf58-f62e-11e7-87b8-652acbbec394.png)

**Comment by AlexMuriithi** [comment]
@ngarawakimani We got it all wrong and I've requested the client to show an example of what she wanted.

**What we build**

![screenshot_3](https://user-images.githubusercontent.com/4029811/34943800-432d10ec-fa0e-11e7-928d-233d59e4a0fe.png)

**What she wanted example below**

![screenshot_4](https://user-images.githubusercontent.com/4029811/34943835-62a8b386-fa0e-11e7-8a5f-df38b89a2a10.png)

**Comment by Jchegenye** [comment]
@AlexMuriithi @mercywanjau  This has been fixed for now

**Comment by AlexMuriithi** [comment]
@ngarawakimani @Jchegenye forget about the widget just add this phone number: 0720888755

**Comment by Jchegenye** [comment]
Fixed @AlexMuriithi  @mercywanjau
